### ISSUE TITLE
Cant launch multi_turtlebot3.launch in ROS Noetic

### ISSUE THREAD

**Issue by aaronchongth** [ROBOTIS-GIT/turtlebot3_simulations#130]
Hello there!

I am having trouble running the multi Turtlebot3 world and Turtlebot3 house world. Any help would be appreciated, thanks! Here is my setup,

Ubuntu 20.04
ROS Noetic

Build instructions,
```
mkdir -p ~/test_ws/src
cd ~/test_ws/src
git clone https://github.com/ROBOTIS-GIT/turtlebot3
git clone https://github.com/ROBOTIS-GIT/turtlebot3_simulations

cd ~/test_ws
rosdep install --from-paths src --ignore-src --rosdistro noetic -yr

# Other dependencies I have found that were not automatically installed using rosdep
sudo apt install ros-noetic-gazebo-ros-pkgs ros-noetic-dwa-local-planner 

cd ~/test_ws
source /opt/ros/noetic/setup.bash
colcon build
```

These are the logs for running the house world, similar to the multi Turtlebot3 world, with `gazebo` getting stuck on the loading screen,
```
aaron@ws:~/test_ws1$ export TURTLEBOT3_MODEL=burger; roslaunch turtlebot3_gazebo turtlebot3_house.launch 
... logging to /home/aaron/.ros/log/1efd41c4-30ca-11eb-b7d0-0d8eee8c6707/roslaunch-ws-37980.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

xacro: in-order processing became default in ROS Melodic. You can drop the option.
started roslaunch server http://ws:33865/

SUMMARY
========

PARAMETERS
 * /gazebo/enable_ros_network: True
 * /robot_description: <?xml version="1....
 * /rosdistro: noetic
 * /rosversion: 1.15.8
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    spawn_urdf (gazebo_ros/spawn_model)

auto-starting new master
process[master]: started with pid [37990]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 1efd41c4-30ca-11eb-b7d0-0d8eee8c6707
process[rosout-1]: started with pid [38000]
started core service [/rosout]
process[gazebo-2]: started with pid [38003]
process[gazebo_gui-3]: started with pid [38011]
process[spawn_urdf-4]: started with pid [38017]
[ INFO] [1606493023.695570938]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1606493023.696700630]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1606493023.788548749]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1606493023.789496346]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
[ INFO] [1606493024.781440176]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1606493024.800089857]: Physics dynamic reconfigure ready.
```

After trying to shut it down with Ctrl+C, this was the rest of the console prints in the same terminal,
```
^C[spawn_urdf-4] killing on exit
[gazebo_gui-3] killing on exit
[gazebo-2] killing on exit
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_service.py", line 522, in call
    responses = transport.receive_once()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 737, in receive_once
    self.stat_bytes += recv_buff(sock, b, p.buff_size)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 109, in recv_buff
    raise TransportTerminated("unable to receive data from sender, check sender's logs for details")
rospy.exceptions.TransportTerminated: unable to receive data from sender, check sender's logs for details

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ros/noetic/lib/gazebo_ros/spawn_model", line 239, in <module>
    exit_code = sm.run()
  File "/opt/ros/noetic/lib/gazebo_ros/spawn_model", line 183, in run
    success = gazebo_interface.spawn_urdf_model_client(self.args.model, model_xml, self.args.robot_namespace,
  File "/opt/ros/noetic/lib/python3/dist-packages/gazebo_ros/gazebo_interface.py", line 32, in spawn_urdf_model_client
    resp = spawn_urdf_model(model_name, model_xml, robot_namespace, initial_pose, reference_frame)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_service.py", line 442, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_service.py", line 530, in call
    raise rospy.exceptions.ROSInterruptException("node shutdown interrupted service call")
rospy.exceptions.ROSInterruptException: node shutdown interrupted service call
[gazebo_gui-3] escalating to SIGTERM
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```

**Comment by aaronchongth** [comment]
Turns out it was just taking a long time to download the world, closing this.
